config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :posts, only: [:index, :show]
  get 'posts/:id/share/:social_media', to: 'posts#share', as: :share_post


  namespace :admin do
    resources :posts, except: %i[new destroy edit]
    resources :analytics, only: :index
    get 'cms/write', to: 'posts#new', as: :new_post
    put 'posts/:id/publish', to: 'posts#publish', as: :publish_post
    get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
    put 'posts/:id/unpublish', to: 'posts#unpublish', as: :unpublish_post
    delete 'posts/:id', to: 'posts#destroy', as: :destroy_post

    get '/login', to: 'sessions#new'
    post '/sessions', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

  end

  get "/about/", to: "about#show"

  get '/sitemap.xml.gz', to: redirect("https://#{Rails.application.credentials.dig(:aws, :prod, :sitemap_bucket)}.s3.#{Rails.application.credentials.dig(:aws, :region)}.amazonaws.com/sitemap.xml.gz")

  get '/feed.xml', to: "posts#rss_feed", as: :rss_feed, constraints: { format: 'rss' }

  namespace :api do
    post 'subscriptions/register', to: 'subscriptions#register', as: :new_subscription
  end
end

app/views/shared/_admin_edit_buttons.html.erb
<% if @post.draft? %>

  <%= button_to "Publish", admin_publish_post_path(id: @post.id), method: :put,
    class: "float-right bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mx-2"  %>
<% elsif @post.published? %>
  <%= button_to "Unpublish", admin_unpublish_post_path(id: @post.id), method: :put,
    class: "float-right bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mx-2"  %>
<% end %>
<%= button_to "Delete", admin_destroy_post_path(id: @post.id), method: :delete, class: "float-right bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded mx-2"  %>
<%= button_to "Edit", admin_edit_post_path(id: @post.id), method: :get,
  class: "float-right bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded mx-2"  %>

app/views/shared/_footer.html.erb
<footer class="font-semibold bg-gradient-to-r from-neutral-100 to-neutral-200 dark:from-indigo-700 dark:to-blue-900">
  <div class="px-10 py-20 text-5xl text-white lg:px-0 lg:py-12 lg:m-auto lg:w-3/4 lg:text-xl">
    <%= render partial: 'shared/newsletter_subscription' %>
  </div>

  <div class="w-full py-10 bg-gray-900 lg:py-5">
    <ul class="tracking-tight text-center">
      <li class="inline-block pr-8 lg:pr-6">
        <a href="https://twitter.com/anakbns"
           class="icon-26 twitter"
           title="Twitter"
           target="_blank">
          <svg viewBox="0 0 512 512" class="w-16 lg:w-8 fill-white">
            <path d="M419.6 168.6c-11.7 5.2-24.2 8.7-37.4 10.2 13.4-8.1 23.8-20.8 28.6-36 -12.6 7.5-26.5 12.9-41.3 15.8 -11.9-12.6-28.8-20.6-47.5-20.6 -42 0-72.9 39.2-63.4 79.9 -54.1-2.7-102.1-28.6-134.2-68 -17 29.2-8.8 67.5 20.1 86.9 -10.7-0.3-20.7-3.3-29.5-8.1 -0.7 30.2 20.9 58.4 52.2 64.6 -9.2 2.5-19.2 3.1-29.4 1.1 8.3 25.9 32.3 44.7 60.8 45.2 -27.4 21.4-61.8 31-96.4 27 28.8 18.5 63 29.2 99.8 29.2 120.8 0 189.1-102.1 185-193.6C399.9 193.1 410.9 181.7 419.6 168.6z"/>
          </svg><!--[if lt IE 9]><em>Twitter</em><![endif]-->
        </a>
      </li>
      <li class="inline-block pr-8 lg:pr-6">
        <a href="https://github.com/anansilva"
           class="icon-13 github"
           title="GitHub"
           target="_blank">
          <svg viewBox="0 0 512 512" class="w-16 lg:w-8 fill-white">
            <path d="M256 70.7c-102.6 0-185.9 83.2-185.9 185.9 0 82.1 53.3 151.8 127.1 176.4 9.3 1.7 12.3-4 12.3-8.9V389.4c-51.7 11.3-62.5-21.9-62.5-21.9 -8.4-21.5-20.6-27.2-20.6-27.2 -16.9-11.5 1.3-11.3 1.3-11.3 18.7 1.3 28.5 19.2 28.5 19.2 16.6 28.4 43.5 20.2 54.1 15.4 1.7-12 6.5-20.2 11.8-24.9 -41.3-4.7-84.7-20.6-84.7-91.9 0-20.3 7.3-36.9 19.2-49.9 -1.9-4.7-8.3-23.6 1.8-49.2 0 0 15.6-5 51.1 19.1 14.8-4.1 30.7-6.2 46.5-6.3 15.8 0.1 31.7 2.1 46.6 6.3 35.5-24 51.1-19.1 51.1-19.1 10.1 25.6 3.8 44.5 1.8 49.2 11.9 13 19.1 29.6 19.1 49.9 0 71.4-43.5 87.1-84.9 91.7 6.7 5.8 12.8 17.1 12.8 34.4 0 24.9 0 44.9 0 51 0 4.9 3 10.7 12.4 8.9 73.8-24.6 127-94.3 127-176.4C441.9 153.9 358.6 70.7 256 70.7z"/>
          </svg><!--[if lt IE 9]><em>GitHub</em><![endif]-->
        </a>
      </li>
      <li class="inline-block pr-8 lg:pr-6">
        <a href="https://linkedin.com/in/anans"
           class="icon-17 linkedin"
           title="LinkedIn"
           target="_blank">
          <svg viewBox="0 0 512 512" class="w-16 lg:w-8 fill-white">
            <path d="M186.4 142.4c0 19-15.3 34.5-34.2 34.5 -18.9 0-34.2-15.4-34.2-34.5 0-19 15.3-34.5 34.2-34.5C171.1 107.9 186.4 123.4 186.4 142.4zM181.4 201.3h-57.8V388.1h57.8V201.3zM273.8 201.3h-55.4V388.1h55.4c0 0 0-69.3 0-98 0-26.3 12.1-41.9 35.2-41.9 21.3 0 31.5 15 31.5 41.9 0 26.9 0 98 0 98h57.5c0 0 0-68.2 0-118.3 0-50-28.3-74.2-68-74.2 -39.6 0-56.3 30.9-56.3 30.9v-25.2H273.8z"/>
          </svg><!--[if lt IE 9]><em>LinkedIn</em><![endif]-->
        </a>
      </li>

      <li class="inline-block">
        <a href="<%= rss_feed_url(format: 'rss') %>"
           target="_blank"
           class="icon-21 rss"
           title="RSS">
          <svg viewBox="0 0 512 512" class="w-16 lg:w-8 fill-white">
            <path d="M201.8 347.2c0 20.3-16.5 36.8-36.8 36.8 -20.3 0-36.8-16.5-36.8-36.8s16.5-36.8 36.8-36.8C185.3 310.4 201.8 326.8 201.8 347.2zM128.2 204.7v54.5c68.5 0.7 124 56.3 124.7 124.7h54.5C306.7 285.3 226.9 205.4 128.2 204.7zM128.2 166.6c57.9 0.3 112.3 22.9 153.2 63.9 41 41 63.7 95.5 63.9 153.5h54.5c-0.3-149.9-121.7-271.4-271.6-271.9V166.6L128.2 166.6z"/>
          </svg><!--[if lt IE 9]><em>RSS</em><![endif]-->
        </a>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_meta_tags.html.erb
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<meta name="keywords" content="<%= meta_keywords %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

<!-- Linked Card data -->
<meta prefix="og: http://ogp.me/ns#" property="og:type" content="website" />
<meta prefix="og: http://ogp.me/ns#" property="og:title" content="<% meta_title %>" />
<meta prefix="og: http://ogp.me/ns#" property="og:description" content="<% meta_description %>" />
<meta prefix="og: http://ogp.me/ns#" property="og:image" content="<% meta_image %>" />
<meta prefix="og: http://ogp.me/ns#" property="og:url" content="<% request.original_url %>" />

app/views/shared/_navbar.html.erb
<header class="flex items-center px-10 pb-5 lg:px-5">
  <div class="flex-grow pt-10 text-6xl font-extrabold tracking-tighter text-transparent lg:pt-5 lg:text-2xl bg-clip-text bg-gradient-to-r from-indigo-500 to-blue-800">
    <a href="/">Ana Nunes da Silva</a>
  </div>

  <div class="pt-10 text-4xl font-semibold sm:hidden lg:block lg:pt-5 lg:flex-grow lg:text-right text-md lg:text-xl">
    <ul class="tracking-tight">
      <li class="inline">
        <%= link_to 'About', about_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
      </li>
      <li class="inline">
        <%= link_to 'Posts', posts_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
      </li>
      <% if current_user %>
        <li class="inline">
          <%= link_to 'Preview', admin_posts_path, method: :get, class: "py-3 pr-4 px-6 hover:underline" %>
        </li>
        <li class="inline">
          <%= link_to 'New Post', admin_new_post_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
        </li>
        <li class="inline">
          <%= link_to 'Dashboard', admin_analytics_path, method: :get, class: "py-4 pr-4 px-6 hover:underline" %>
        </li>
        <li class="inline">
          <%= link_to 'Logout', admin_logout_path, method: :delete, class: "py-4 pr-4 px-6 hover:underline" %>
        </li>
      <% end %>
    </ul>
  </div>

  <%# data-controller with the name of the controller that will listen to the events on this element %>
  <div class="relative inline-block pt-10 text-center lg:hidden" data-controller="menu">
  <%# data-action with the event type that will trigger a toggle function on the menu controller %>
    <button data-action="click->menu#toggle" type="button" class="inline-flex justify-center w-full px-4 py-2 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500"
      id="options-menu" aria-haspopup="true" aria-expanded="true">
      <svg viewBox="0 0 100 80" width="60" height="60" class="dark:fill-white">
          <rect width="100" height="20" rx="8"></rect>
          <rect y="30" width="100" height="20" rx="8"></rect>
          <rect y="60" width="100" height="20" rx="8"></rect>
      </svg>
    </button>

  <%# data-target what the target of our function will be %>
  <div class="absolute right-0 hidden mt-2 bg-white shadow-lg w-96 origin-top-right rounded-md ring-1 ring-black ring-opacity-5"
    data-menu-target="toggleable">
      <div class="py-6" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
        <a href="/about" class="block px-4 py-6 text-5xl text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">About</a>
        <a href="/posts" class="block px-4 py-6 text-5xl text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">Posts</a>
      </div>
    </div>
  </div>

</header>

app/views/shared/_newsletter_subscription.html.erb
<div data-controller="subscription" class="text-center"  %>
  <h2 class="mb-4 text-5xl tracking-wide text-gray-700 dark:text-white lg:mb-2 lg:text-2xl">Subscribe to get future posts in your mailbox</h2>
  <%= form_with url: api_new_subscription_url,
    data: { action: "ajax:success->subscription#onSuccess ajax:error->subscription#onError" },
    method: :post do |form| %>
    <div data-subscription-target="email">
      <%= form.email_field :email, placeholder: "Your email address",
        class: "text-4xl lg:text-base p-4 w-full mx-auto mt-6 lg:w-4/12 lg:py-2 lg:px-2 lg:m-2 border rounded focus:outline-none focus:border-indigo-500 text-gray-900 dark:text-gray-300 dark:bg-gray-900" %>
      <%= form.submit 'subscribe', id: "newsletter-btn",
        class: "text-4xl w-full mx-auto lg:text-base lg:w-2/12 lg:m-2 my-8 p-4 cursor-pointer border-neutral-100 lg:py-2 lg:px-0 font-bold rounded focus:outline-none bg-indigo-500" %>
    </div>
  <% end %>
</div>

app/views/shared/_pagination.html.erb
<div class="flex items-center justify-center my-10 text-4xl font-semibold tracking-wide text-indigo-700 lg:text-xl dark:text-indigo-500" %>
  <% if  pagination.previous_page? %>
    <%= link_to 'First', posts_path(page: 1) %>
    <%= link_to '< Previous', posts_path(page: pagination.previous_page), class: "lg:ml-6 ml-12" %>
  <% else %>
    <p class="text-gray-300 dark:text-gray-700">First</p>
    <p class="text-gray-300 lg:ml-6 dark:text-gray-700">&#60; Previous</p>
  <% end %>
  <p class="ml-12 font-normal text-gray-900 lg:ml-6 lg:text-base dark:text-gray-300"><%= "Page #{pagination.page} of #{pagination.total_pages}" %></p>
  <% if pagination.next_page? %>
    <%= link_to 'Next >', posts_path(page: pagination.next_page), class: "lg:ml-6 ml-12" %>
    <%= link_to 'Last', posts_path(page: pagination.total_pages), class: "lg:ml-6 ml-12" %>
  <% else %>
    <p class="ml-12 text-gray-300 lg:ml-6 dark:text-gray-700">Next &#62;</p>
    <p class="ml-12 text-gray-300 lg:ml-6 dark:text-gray-700">Last </p>
  <% end %>
</div>

app/views/shared/_post_card.html.erb
<div class="w-full pb-12 mb-6 lg:pr-4 lg:w-1/3 xl:w-1/3">
  <article class="overflow-hidden">
    <% if post.cover_image.attached? %>
      <%= image_tag post.cover_image.variant(resize_to_limit: [300, 300]), alt: "#{post.title} cover image", class: 'h-full w-full cursor-pointer' %>
    <% end %>
    <div class="container pt-8 mx-auto leading-relaxed lg:px-4 lg:mx-0 lg:pt-4 lg:leading-normal">
      <h2 class="mb-2 text-5xl font-extrabold tracking-wide lg:mb-1 lg:text-2xl hover:underline">
        <%= link_to post.title, link_to_post(post) %>&nbsp;<%= '[DRAFT]' if post.draft? %>
      </h2>
      <p class="mb-4 text-3xl text-gray-600 lg:mb-2 lg:text-sm">
        <%= post.published_at&.strftime('%b, %Y') %>
      <p>
      <p class="overflow-hidden text-4xl leading-relaxed text-gray-600 dark:text-gray-50 overflow-ellipsis lg:text-base">
        <%= post.intro %><br>
      </p>
    </div>
  </article>
</div>

app/views/shared/_post_intro.html.erb
<div class="w-full sm:w-full md:w-full lg:w-1/3 xl:1/4 p-2 mb-4">
  <div class="text-gray-700 text-center bg-gray-100 p-2">
    <%= post.title %>
  </div>
  <div class="text-gray-700 text-center bg-gray-100 p-2">
    <%= post.intro %>
  </div>
</div>

app/views/shared/_post_views.html.erb
<p>
  Total views: <%=  @post_views[:total_views] %>
  Unique views: <%=  @post_views[:unique_total_views] %>
<p>

app/views/shared/_tags.html.erb
<h1 class="px-0 text-5xl font-bold leading-tight tracking-tighter text-black dark:text-gray-50 lg:text-4xl">
  I like to write about:
</h1>

<% published_tags.each do |tag_name| %>
  <%= link_to "##{tag_name}", filter_posts(tag_name),
    class: "mr-4 lg:mr-2 hover:underline sm:text-3xl lg:text-sm font-bold uppercase text-indigo-500"%>
<% end %>