config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :posts, only: [:index, :show]
  get 'posts/:id/share/:social_media', to: 'posts#share', as: :share_post


  namespace :admin do
    resources :posts, except: %i[new destroy edit]
    resources :analytics, only: :index
    get 'cms/write', to: 'posts#new', as: :new_post
    put 'posts/:id/publish', to: 'posts#publish', as: :publish_post
    get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
    put 'posts/:id/unpublish', to: 'posts#unpublish', as: :unpublish_post
    delete 'posts/:id', to: 'posts#destroy', as: :destroy_post

    get '/login', to: 'sessions#new'
    post '/sessions', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

  end

  get "/about/", to: "about#show"

  get '/sitemap.xml.gz', to: redirect("https://#{Rails.application.credentials.dig(:aws, :prod, :sitemap_bucket)}.s3.#{Rails.application.credentials.dig(:aws, :region)}.amazonaws.com/sitemap.xml.gz")

  get '/feed.xml', to: "posts#rss_feed", as: :rss_feed, constraints: { format: 'rss' }

  namespace :api do
    post 'subscriptions/register', to: 'subscriptions#register', as: :new_subscription
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :history

  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts

  has_one_attached :cover_image

  validates :title, presence: true
  validates :intro, presence: true
  validates :body, presence: true

  enum status: { draft: 0, published: 1 }
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action :authenticate_user!

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)

      if @post.save!
        ::Tags::UpdatePostTags.call(@post, tag_names)
        redirect_to admin_post_path(@post),
                    notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    def edit
      @post = Post.friendly.find(params[:id])

      render :new
    end

    def update
      @post = Post.friendly.find(params[:id])

      if @post.update!(post_params)
        ::Tags::UpdatePostTags.call(@post, tag_names)
        redirect_to admin_post_path(@post),
                    notice: 'Post was successfully updated.'
      else
        render :new
      end
    end

    def publish
      @post = Post.find(params[:id])

      if ::Posts::PublishPost.call(@post)
        redirect_to admin_post_path(@post),
                    notice: 'Post was published'
      else
        redirect_to admin_post_path(@post),
                    notice: 'Post is still draft. Maybe something is missing?'
      end
    end

    def unpublish
      @post = Post.find(params[:id])

      if @post.draft!
        redirect_to admin_post_path(@post), notice: 'Post is now a draft'
      else
        redirect_to admin_post_path(@post)
      end
    end

    def destroy
      post = Post.find(params[:id])
      post_title = post.title

      if post.destroy
        redirect_to admin_posts_path,
                    notice: "#{post_title} was successfully destroyed."
      else
        redirect_to admin_posts_path
      end
    end

    def show
      @post = Post.friendly.find(params[:id])

      render 'posts/show', post: @post
    end

    def index
      @posts = Query::Posts.call(tag: params[:tag])

      render 'admin/posts/index', posts: @posts
    end

    private

    def tag_names
      tag_params.fetch(:tags, '').split(', ')
    end

    def tag_params
      params.require(:post).permit(:tags)
    end

    def post_params
      params.require(:post).permit(:title, :body, :intro, :cover_image, :keywords)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ::Pagination
  POSTS_PER_PAGE = 6

  def index
    @pagination, @posts = paginate(collection: posts, params: page_params)
    @tag = params[:tag]
  end

  def show
    @post = Post.published.friendly.find(params[:id])
  end

  def rss_feed
    @posts = Post.published.last(10)
  end

  def share
    @post = Post.published.friendly.find(params[:id])

    social_media_url =
      ::Services::MountShareUrl.call(@post, post_url(@post), params[:social_media])

    redirect_to social_media_url
  end

  private

  def page_params
    params.permit(:page).merge(per_page: POSTS_PER_PAGE)
  end

  def posts
    ::Query::Posts.call(tag: params[:tag], status: 'published')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def link_to_post(post)
    return admin_post_path(post) if current_user

    post_path(post) if post.published?
  end

  def all_posts
    return admin_posts_path if current_user

    posts_path
  end

  def filter_posts(tag_name)
    return admin_posts_path(tag: tag_name) if current_user

    posts_path(tag: tag_name)
  end

  def markdown_to_html(text)
    options = %i[hard_wrap autolink no_intra_emphasis fenced_code_blocks tables]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/views/posts/index.html.erb
<% content_for :meta_title, 'Blog Posts' + " #{@tag}" %>
<% content_for :meta_description, 'thoughts and learnings on software development' %>

<div class="px-10 pb-4 m-auto mt-8 lg:px-0 lg:w-3/4 leading-10">

  <%= render partial: 'shared/tags' %>

  <div class="flex flex-wrap justify-start w-full mx-auto mt-10 lg:container">

    <% @posts.each do |post| %>
      <%= render partial: 'shared/post_card', locals: { post: post } %>
    <% end %>
  </div>
</div>

<%= render partial: 'shared/pagination', locals: { pagination: @pagination } %>

app/views/posts/show.html.erb
<% content_for :meta_title, @post.title %>
<% content_for :meta_description, @post.intro %>
<% content_for :meta_keywords, @post.keywords %>
<% content_for :meta_image, url_for(@post.cover_image.variant(resize_to_fill: [1200, 600])) %>

<article class="px-12 my-8 lg:px-0 lg:mx-auto lg:container lg:my-0">

  <% if @post.cover_image.attached? %>
    <%= image_tag @post.cover_image, alt: "#{@post.title}", class: 'w-full cursor-pointer' %>
  <% end %>

  <div class="pt-8 bg-neutral-50 dark:bg-gray-900 lg:relative lg:pt-8 lg:pb-40 lg:px-16 lg:mx-36 post-intro">
    <% if current_page?(admin_post_path(@post)) %>
      <%= render partial: 'shared/admin_edit_buttons', locals: { post: @post } %>
    <% end %>
    <% @post.tags.each do |tag| %>
      <p class="inline-block mb-4 mr-8 text-3xl font-bold tracking-wide text-left text-indigo-500 rounded-sm lg:mb-2 lg:mr-6 lg:mr-2 sm:text-4xl hover-text-indigo-600 hover:text-indigo-800 lg:text-lg">
        <%= link_to tag.name, posts_path(tag: tag.name)  %>
      </p>
    <% end %>

    <p class="inline-block mb-2 text-2xl text-left text-gray-600 lg:tracking-wide lg:text-sm">
      <%= @post.published_at&.strftime('%b, %Y')%>
    </p>

    <h1 class="mb-8 text-6xl font-black tracking-wide lg:text-4xl">
      <%= @post.title %> <%= '[PREVIEW]' if @post.draft? %>
    </h1>

    <div class="pt-6 pb-2 mb-8 text-5xl font-bold leading-relaxed border-t border-b border-gray-300 dark:border-indigo-500 lg:text-lg">
      <%= @post.intro %>
      </br>
      <div class="text-right text-indigo-500">
        <a href="<%= share_post_url(@post, 'twitter') %>" class="inline-block font-normal underline cursor-pointer sm:text-4xl lg:text-sm hover:text-indigo-600">
          Share
        </a>
        <a href="<%= share_post_url(@post, 'twitter') %>" class="inline-block align-middle" target="_blank">
          <svg viewBox="0 0 512 512" class="w-14 lg:w-7 fill-indigo-500">
            <path d="M419.6 168.6c-11.7 5.2-24.2 8.7-37.4 10.2 13.4-8.1 23.8-20.8 28.6-36 -12.6 7.5-26.5 12.9-41.3 15.8 -11.9-12.6-28.8-20.6-47.5-20.6 -42 0-72.9 39.2-63.4 79.9 -54.1-2.7-102.1-28.6-134.2-68 -17 29.2-8.8 67.5 20.1 86.9 -10.7-0.3-20.7-3.3-29.5-8.1 -0.7 30.2 20.9 58.4 52.2 64.6 -9.2 2.5-19.2 3.1-29.4 1.1 8.3 25.9 32.3 44.7 60.8 45.2 -27.4 21.4-61.8 31-96.4 27 28.8 18.5 63 29.2 99.8 29.2 120.8 0 189.1-102.1 185-193.6C399.9 193.1 410.9 181.7 419.6 168.6z"/>
          </svg><!--[if lt IE 9]><em>Twitter</em><![endif]-->
        </a>
      </div>
    </div>
  </div>

  <div class="lg:block lg:relative">
    <div id="post-body" class="mb-20 text-5xl font-normal leading-relaxed lg:text-lg lg:px-16 lg:mx-36 lg:-mt-40">
      <%= markdown_to_html(@post.body) %>
    </div>
    <div class="absolute top-0 left-0 h-full pl-12 text-3xl text-indigo-500 lg:block sm:hidden">
      <ul class="sticky top-0">
        <li class="block pt-5">
          <a href="<%= share_post_url(@post, 'twitter') %>" target="_blank">
            <svg viewBox="0 0 512 512" class="w-10 fill-indigo-500">
              <path d="M419.6 168.6c-11.7 5.2-24.2 8.7-37.4 10.2 13.4-8.1 23.8-20.8 28.6-36 -12.6 7.5-26.5 12.9-41.3 15.8 -11.9-12.6-28.8-20.6-47.5-20.6 -42 0-72.9 39.2-63.4 79.9 -54.1-2.7-102.1-28.6-134.2-68 -17 29.2-8.8 67.5 20.1 86.9 -10.7-0.3-20.7-3.3-29.5-8.1 -0.7 30.2 20.9 58.4 52.2 64.6 -9.2 2.5-19.2 3.1-29.4 1.1 8.3 25.9 32.3 44.7 60.8 45.2 -27.4 21.4-61.8 31-96.4 27 28.8 18.5 63 29.2 99.8 29.2 120.8 0 189.1-102.1 185-193.6C399.9 193.1 410.9 181.7 419.6 168.6z"/>
            </svg><!--[if lt IE 9]><em>Twitter</em><![endif]-->
          </a>
        </li>
        <li class="block mt-5">
          <a href="<%= share_post_url(@post, 'linkedin') %>" target="_blank">
            <svg viewBox="0 0 512 512" class="w-10 fill-indigo-500">
              <path d="M186.4 142.4c0 19-15.3 34.5-34.2 34.5 -18.9 0-34.2-15.4-34.2-34.5 0-19 15.3-34.5 34.2-34.5C171.1 107.9 186.4 123.4 186.4 142.4zM181.4 201.3h-57.8V388.1h57.8V201.3zM273.8 201.3h-55.4V388.1h55.4c0 0 0-69.3 0-98 0-26.3 12.1-41.9 35.2-41.9 21.3 0 31.5 15 31.5 41.9 0 26.9 0 98 0 98h57.5c0 0 0-68.2 0-118.3 0-50-28.3-74.2-68-74.2 -39.6 0-56.3 30.9-56.3 30.9v-25.2H273.8z"/>
            </svg><!--[if lt IE 9]><em>LinkedIn</em><![endif]-->
          </a>
        </li>
      </ul>
    </div>
  </div>
</article>